apiVersion: v130893
data:
  config.yml: |-
    redis:
      url: '192.168.0.201'
      password: ''
      user: ''
      port: '30893'
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: eve-graphql